#ifndef __PPPOS_CLIENT_MAIN_H__
#define __PPPOS_CLIENT_MAIN_H__

#include <stdint.h>
#include "app_uart.h"




//#define CONFIG_LWIP_PPP_SUPPORT y
//#define CONFIG_LWIP_PPP_NOTIFY_PHASE_SUPPORT y
//#define CONFIG_LWIP_PPP_PAP_SUPPORT y
//
//#define CONFIG_LWIP_PPP_ENABLE_IPV6 n
//
//#define CONFIG_EXAMPLE_MODEM_DEVICE_SIM800 y
//#define CONFIG_EXAMPLE_MODEM_DEVICE_BG96 n
//
//#define CONFIG_ESP_SYSTEM_PANIC_PRINT_HALT y
//#define CONFIG_ESP32_PANIC_PRINT_HALT y

//#define CONFIG_LWIP_TCPIP_TASK_STACK_SIZE 4096

#define CONFIG_EXAMPLE_MODEM_UART_TX_PIN UART2_TXD
#define CONFIG_EXAMPLE_MODEM_UART_RX_PIN UART2_RXD

#define CONFIG_EXAMPLE_MODEM_PPP_APN "UNINET"//"lpwa.vodafone.com"

#define CONFIG_EXAMPLE_MQTT_TEST_DATA "esp32-pppos"


//#define CONFIG_EXAMPLE_MODEM_DEVICE_SIM7600	1
//#define CONFIG_EXAMPLE_MODEM_DEVICE_CUSTOM	1



#define CONFIG_EXAMPLE_FLOW_CONTROL_NONE


#define CONFIG_EXAMPLE_MODEM_UART_RX_BUFFER_SIZE	1300//1024
#define CONFIG_EXAMPLE_MODEM_UART_TX_BUFFER_SIZE	1300//512
#define CONFIG_EXAMPLE_MODEM_UART_EVENT_QUEUE_SIZE	30
#define CONFIG_EXAMPLE_MODEM_UART_EVENT_TASK_STACK_SIZE	4096//uart_task  ,4G modem 线程的 stack,    2048
#define CONFIG_EXAMPLE_MODEM_UART_EVENT_TASK_PRIORITY	6//5



void Net_Exchange_Cellular4G(void); 


#endif
